version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - todo_app
      - shorturl_app
    networks:
      - timuredu_network

  todo_app:
    image: timuredu/todo_app:latest
    container_name: todo_container
    expose:
      - "80"
    networks:
      - timuredu_network

  shorturl_app:
    image: timuredu/shorturl_app:latest
    container_name: shorturl_container
    expose:
      - "80"
    networks:
      - timuredu_network

networks:
  timuredu_network:
